version: '3'

services:
    nginx:
      build:
        context: ./nginx
      container_name: php_nginx
      volumes:
        - ${APP_CODE_WEB_PATH_HOST}:${APP_CODE_WEB_PATH_CONTAINER}
        - ${NGINX_WEB_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_WEB_SITE_PATH}:/etc/nginx/sites-available/web.conf
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      ports:
        - "${NGINX_WEB_HOST_HTTP_PORT}:80"
        - "${NGINX_WEB_HOST_HTTPS_PORT}:443"
      depends_on:
        - web
      links:
        - web  
      networks:
        - frontend
        - backend

    web:
      build:
        context: ./php-fpm
        args:
          - LARADOCK_PHP_VERSION=${PHP_VERSION}
          - INSTALL_APCU=${PHP_FPM_INSTALL_APCU}
          - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
          - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
          - INSTALL_PCNTL=${PHP_FPM_INSTALL_PCNTL}
          - INSTALL_COMPOSER=${PHP_FPM_INSTALL_COMPOSER}
          - INSTALL_GIT=${PHP_FPM_INSTALL_GIT}
          - INSTALL_ZIP=${PHP_FPM_INSTALL_ZIP}
          - INSTALL_ZIP_ARCHIVE=${PHP_FPM_INSTALL_ZIP_ARCHIVE}
          - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
          - INSTALL_IMAGEMAGICK=${PHP_FPM_INSTALL_IMAGEMAGICK}
          - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
          - INSTALL_NPM=${PHP_FPM_INSTALL_NPM}
          - INSTALL_CRON=${PHP_FPM_INSTALL_CRON}
          - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
          - WORK_DIR=${APP_CODE_WEB_PATH_CONTAINER}
          - NODE_VERSION=${NODE_VERSION}
      container_name: php_web
      environment:
        XDEBUG_CONFIG: "remote_host=host.docker.internal"
        PHP_IDE_CONFIG: "serverName=localhost"
      volumes:
        - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ./php-fpm/cron/crontab_web:/etc/crontab
        - ${APP_CODE_WEB_PATH_HOST}:${APP_CODE_WEB_PATH_CONTAINER}   
        - ${DATA_PATH_HOST}/sqlite:/db     
      expose:
        - "9000"
      depends_on:
        - db
        - redis
      networks:
        - backend

    consumers:
      build:
        context: ./php-fpm-consumers
        args:
          - LARADOCK_PHP_VERSION=${PHP_VERSION}
          - INSTALL_APCU=${PHP_FPM_INSTALL_APCU}
          - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
          - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
          - INSTALL_PCNTL=${PHP_FPM_INSTALL_PCNTL}
          - INSTALL_COMPOSER=${PHP_FPM_INSTALL_COMPOSER}
          - INSTALL_GIT=${PHP_FPM_INSTALL_GIT}
          - INSTALL_ZIP=${PHP_FPM_INSTALL_ZIP}
          - INSTALL_ZIP_ARCHIVE=${PHP_FPM_INSTALL_ZIP_ARCHIVE}
          - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
          - INSTALL_IMAGEMAGICK=${PHP_FPM_INSTALL_IMAGEMAGICK}
          - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
          - INSTALL_SUPERVISOR=${PHP_FPM_INSTALL_SUPERVISOR}
      container_name: php_consumers
      volumes:
        - ./php-fpm-consumers/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ./php-fpm-consumers/supervisor/web.conf:/etc/supervisor/conf.d/web.conf
        - ${APP_CODE_WEB_PATH_HOST}:${APP_CODE_WEB_PATH_CONTAINER}
      expose:
        - "9000"
      depends_on:
        - db
        - redis
      networks:
        - backend                 

    db:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      container_name: php_db
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend

    redis:
      build: ./redis
      container_name: php_redis
      volumes:
        - ${DATA_PATH_HOST}/redis:/data
      ports:
        - "${REDIS_PORT}:6379"
      networks:
        - backend  

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  db:
    driver: ${VOLUMES_DRIVER}   
  redis:
    driver: ${VOLUMES_DRIVER} 

